# ARQUIVO: frontend/Dockerfile

# Estágio 1: Imagem base
FROM node:lts-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependência primeiro para aproveitar o cache do Docker
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código da aplicação
COPY . .

# Expõe a porta padrão do Vite
EXPOSE 5173

# O comando para iniciar a aplicação será definido no docker-compose.yml
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]