# ARQUIVO: nginx/Dockerfile

# Usa a imagem oficial do Nginx baseada em Alpine
FROM nginx:alpine

# Remove a configuração padrão para evitar conflitos
RUN rm /etc/nginx/conf.d/default.conf

# Copia o nosso arquivo de configuração para o diretório correto
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80